### ISSUE TITLE
PX4 Arming Problem

### ISSUE THREAD

**Issue by ybelilov** [monemati/PX4-ROS2-Gazebo-YOLOv8#3]
The installation was successful.
And all components except PX4 working well !

PX4 erros:
**Compass Sensor 0 missing**
**Accel #0 fail: STALE!** 
**Gyro #0 fail: STALE!** 
![image](https://github.com/monemati/PX4-ROS2-Gazebo-YOLOv8/assets/25921119/f7862839-c82a-4046-9bbf-caac0e770596)
![image](https://github.com/monemati/PX4-ROS2-Gazebo-YOLOv8/assets/25921119/37bea55d-222f-4671-98b3-9a5e9c0fb2b8)

**Comment by monemati** [comment]
@ybelilov Hello, thank you for using my repo. The error you are getting is new to me, I looked into PX4 repo's issues and I saw this from some days ago: https://github.com/PX4/PX4-Autopilot/issues/22767

**Comment by ybelilov** [comment]
@monemati Thank you for sharing this repo!
Fixed this by switching to PX4 commit 97cb933cff6d837e59dd55123804cd78abdca22a
