### ISSUE TITLE
drone cant take off 

### ISSUE THREAD

**Issue by Meriem-ghrissi** [monemati/PX4-ROS2-Gazebo-YOLOv8#7]
when running the last command (ros2 run px4_ros_com offboard_control )on the terminal i get command send but the drone never moves

**Comment by monemati** [comment]
@Meriem-ghrissi Hi. Are you getting any errors in the terminals?

**Comment by Meriem-ghrissi** [comment]
hello, thank you for replying. no i am getting no errors in the terminal but the drone never moves

**Comment by monemati** [comment]
@Meriem-ghrissi Hello. Be sure you are getting the `pxh> INFO  [commander] Ready for takeoff!` message in your px4 terminal then run other controlling commands.

**Comment by monemati** [comment]
@Meriem-ghrissi Then everything should be fine, if it is only from ros side you can try to reinstall it (`Install ROS 2`).
