### ISSUE TITLE
how can i add other objects to the gazebo world

### ISSUE THREAD

**Issue by Meriem-ghrissi** [monemati/PX4-ROS2-Gazebo-YOLOv8#8]
how can i add other objects to the gazebo world

**Comment by monemati** [comment]
@Meriem-ghrissi Hello. You can add other objects by modifying `default.sdf` in world folder. For example if you check the end of the file you can see this part:
```
    <include>
      <pose>280.64 -137.32 2.77 -0.019 -0.008 2.46</pose>
      <uri>model://casual_female</uri>
    </include>
```
With this format you can just add other objects (you can just copy and paste this lines), just don't forget to change the pose of objects.
You can find other models from this [link](https://app.gazebosim.org/fuel/models).
